---
title: "03 Classify"
output: html_document
---

Author: Kaitlin Volk; with edits by Jeff Cegan  
Date: May 19, 2021  
Project HAB with Jodi Ryder  

```{r, include=FALSE}
#load global packages and variables
source("~/Documents/GitHub/hab/code/00_global.R") #adjust to your computer specs
```

### Load and filter data. 
Summary of data:

```{r, echo=FALSE}
load(paste0(dirpath,"hab/data/wqdata_cleaned.rda"))
```

## 1.2 Time series plots for a single location

```{r, echo=FALSE}
#They're pretty messy, especially temp and DO if we don't control for depth.
dat4 %>% filter(loc_id=="TAR20001") %>%             #choose one sample site
  ggplot(aes(x=sample_date,y=value, color=depth)) + #graph values over time, with color displayign depth
  geom_point() + geom_smooth(method = "loess") +    #add loess curve to look at trend
  facet_wrap(~param,nrow=4,scales = "free_y")       #facet by paramter

#What if we do data for a single reservoir instead of a single site? -> Messier
dat4 %>% filter(reservoir=="TAR") %>%               #Choose single reservoir instead of single site
  ggplot(aes(x=sample_date,y=value, color=depth)) + #do the same as above 
  geom_point() + geom_smooth(method = "loess") + facet_wrap(~param,nrow=4,scales = "free_y")
#Surface only
test.graph <-dat4 %>% filter(reservoir=="TAR" & depth==0) %>% #use only data where the depth=0 (surface) 
  ggplot(aes(x=sample_date,y=value)) + geom_point() + geom_smooth(method = "loess") + 
  facet_wrap(~param,nrow=4,scales = "free_y")
test.graph 

#I'm thinking we could have a default (like all data color coded for depth or just surface) 
#and then the ability for the users to select/input a depth or depth range

#The SOW wants a label of how many data points are displayed on the graph. I make a table 
#of these values below but then the code I looked up to add it to a facet with different y axes
#doesn't work and I don't know why
site.nsamples <- dat4 %>% group_by(loc_id, param) %>% summarize(count=n()) %>% ungroup() %>% #Get counts for the number of observations per param per site
  pivot_wider(names_from = param, values_from=count) %>% mutate_all(~replace(., is.na(.), 0)) #give each param a column and replace na's with 0's

reservoir.nsamples<- dat4 %>%  group_by(reservoir, param) %>% summarize(count=n(),   #Get counts for the number of observations per param per reservoir
                                                                        ystar=(0.8 * max(value)))  #y placement for graph (doesn't seem to work though) 

test.graph + geom_text(data=reservoir.nsamples,   #counts from the reservoir.nsamples table
                       aes(y=ystar, x=ymd(2010-01-01), label=paste("N=", count)), #placement and content of label
                       colour="red", inherit.aes=FALSE, parse=TRUE)         #Doesn't work...

#Also adding # samples for each parameter to the reserveroir summary table so it's all in one place
reservoir.summary2 <- reservoir.nsamples %>% select(-4) %>% pivot_wider(names_from = param, values_from=count) %>% #remove graphing column and spread 
  mutate_all(~replace(., is.na(.), 0)) %>% right_join(reservoir.summary, by="reservoir") %>% #replace NAs with 0's
  relocate(n.sites, .after=reservoir) #put number of sites before # of param samples
rm(reservoir.summary) #remove previous version
```

## 1.3 Characterizing reservoirs based on last five years of summer months (may-sept)  
             Oligo   Meso    Eutro  
TP (ug/L)    8       27      84     
TN (mg/L)    .66     .75     1.9  
ChlA (ug/L)  1.7     4.7     14  

```{r, echo=FALSE}
trophic.param <- c("P_total", "N_total","chlA")   #Paramters that we'll use to determine trophic state
summer.months <- c("05", "06", "07", "08", "09")  #Summer months as specified in SOW (May-Sept)

trophicstates <- dat4 %>% 
  filter(param %in% trophic.param & mo %in% summer.months & yr > 2013) %>% #keep only trophic parameters from the summer for the last 5 years
  pivot_wider(names_from= param, values_from = value,values_fn=mean) %>%   #go wide
  group_by(reservoir) %>% 
  summarize(P_total = mean(P_total, na.rm=TRUE),                           #mean total phosphorous for each reservoir
            N_total = mean(N_total, na.rm=TRUE),                           #mean total nitrogen for each reservoir
            chlA = mean(chlA, na.rm=TRUE)) %>%                             #mean chlA for each reservoir
  mutate(troph_P = as.numeric(case_when(P_total < 27 ~ "1",         #use thresholds to determine trophic state based on P
                             P_total >= 27 & P_total < 84 ~ "2",     #1= Oligo, 2= Meso, 3=Eutro
                             P_total > 84 ~ "3",
                             TRUE ~ NA_character_)),
         troph_N = as.numeric(case_when(N_total < .75 ~ "1",         #use thresholds to determine trophic state based on N
                             N_total >= .75 & N_total < 1.9 ~ "2",
                             N_total >= 1.9 ~ "3",
                             TRUE ~ NA_character_)),
         troph_chla= as.numeric(case_when(chlA < 4.7 ~ "1",            #use thresholds to determine trophic state based on chlA
                                 chlA >= 4.7 & chlA < 14 ~ "2",
                                 chlA >= 14 ~ "3",
                                 TRUE ~ NA_character_))) %>% 
  rowwise() %>% mutate(troph_combo =(median(c(troph_P, troph_N, troph_chla), na.rm = T))) %>% #Find th median trophic state
  ungroup %>% mutate(trophic_state= case_when(troph_combo==1 ~"Oligotrophic",   #Recode median trophic state to words for final output
                                              troph_combo==1.5 ~ "Oligo-Mesotrophic",
                                              troph_combo==2 ~ "Mesotrophic",
                                              troph_combo==2.5 ~ "Meso-Eutrotrophic",
                                              troph_combo==3 ~ "Eutrotrophic"))

#Q: Do we want to take the mean or the median of the paramters to base the trophic states on?

#Q: What do we want to do when one parameters disagree on trophic state (i.e. it's eutro for P
# but meso for N and chlA)? We coud take the median or use hyphens (e.g. meso-eutro) 
# I did a combo of both above. 

#Add trophic state to the reservoir summary table with a left join since not all reservoirs have data for a trophic state
reservoir.summary3 <- left_join(reservoir.summary2, trophicstates, by="reservoir") %>% 
  select(-(17:23)) %>% relocate(trophic_state, .after = n.sites) 
rm(reservoir.summary2) #remove previous iteration; reminder, the values for the different parameters are counts of samples
```
